QuemSou/Controllers/FormacaoController.cs
using QuemSou.Models.Business;
using QuemSou.Models.Mapeamento;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuemSou.Controllers
{
    public class FormacaoController : Controller
    {
        // GET: Formacao
        public ActionResult Index()
        {
            var lista = new FormacaoBusiness().ListarFormacao();
            return View(lista);
        }

        public ActionResult Delete(int id)
        {
            if (new FormacaoBusiness().Apagar(id)) 
            return RedirectToAction("index");
            else
                return RedirectToAction("FormacaoERRO");
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View(new Formacao());

        }

        [HttpPost]
        public ActionResult Create(Formacao formacao)
        {
            if (new FormacaoBusiness().Novo(formacao))
                return RedirectToAction("index");
            else
                return RedirectToAction("FormacaoERRO");

        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var formacao = new FormacaoBusiness().ExibirFormacao(id);
            return View(formacao);

        }

        [HttpPost]
        public ActionResult Edit(Formacao formacao)
        {
            if (new FormacaoBusiness().editar(formacao))
                return RedirectToAction("index");
            else
                return RedirectToAction("FormacaoERRO");

        }

        public JsonResult Listar()
        {
            var lista = new FormacaoBusiness().ListarFormacao();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

    }
}

QuemSou/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quem Sou?</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quem Sou", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Experiencia", "index", "experiencia")</li>
                    <li>@Html.ActionLink("Formação", "index", "Formacao")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Projeto TLP II -Pedro Emanoel 98380</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>